sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t inderm/docker-react .


script:
  - docker run -e CI=true inderm/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "dockerreact-env"
    bucket_name: "elasticbeanstalk-us-east-1-378667922359"
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY